// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// energy_cpp
double energy_cpp(const arma::rowvec& state, const arma::rowvec& alpha, const arma::mat& beta);
RcppExport SEXP _graphela_energy_cpp(SEXP stateSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type state(stateSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(energy_cpp(state, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// stpd_cpp
arma::rowvec stpd_cpp(const arma::rowvec& state, const arma::rowvec& alpha, const arma::mat& beta, bool print);
RcppExport SEXP _graphela_stpd_cpp(SEXP stateSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type state(stateSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< bool >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(stpd_cpp(state, alpha, beta, print));
    return rcpp_result_gen;
END_RCPP
}
// rss_cpp
arma::mat rss_cpp(arma::rowvec alpha, arma::mat beta, const arma::uword n, const bool replace);
RcppExport SEXP _graphela_rss_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP nSEXP, SEXP replaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< const bool >::type replace(replaceSEXP);
    rcpp_result_gen = Rcpp::wrap(rss_cpp(alpha, beta, n, replace));
    return rcpp_result_gen;
END_RCPP
}
// findpath_cpp
Rcpp::List findpath_cpp(const arma::rowvec& s0, const arma::rowvec& s1, const arma::rowvec& alpha, const arma::mat& beta, double temp, const double r, const arma::uword iter);
RcppExport SEXP _graphela_findpath_cpp(SEXP s0SEXP, SEXP s1SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP tempSEXP, SEXP rSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type s0(s0SEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(findpath_cpp(s0, s1, alpha, beta, temp, r, iter));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cpp
Rcpp::List ridge_cpp(const arma::mat& sse, const arma::rowvec& alpha, const arma::mat& beta, double temp, const double r, const arma::uword iter, Rcpp::Nullable<arma::uvec> index);
RcppExport SEXP _graphela_ridge_cpp(SEXP sseSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP tempSEXP, SEXP rSEXP, SEXP iterSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sse(sseSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::uvec> >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cpp(sse, alpha, beta, temp, r, iter, index));
    return rcpp_result_gen;
END_RCPP
}
// find_shallow_cpp
arma::uword find_shallow_cpp(const arma::mat& barrier);
RcppExport SEXP _graphela_find_shallow_cpp(SEXP barrierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type barrier(barrierSEXP);
    rcpp_result_gen = Rcpp::wrap(find_shallow_cpp(barrier));
    return rcpp_result_gen;
END_RCPP
}
// prune_cpp
Rcpp::List prune_cpp(arma::mat& barrier, const double th);
RcppExport SEXP _graphela_prune_cpp(SEXP barrierSEXP, SEXP thSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type barrier(barrierSEXP);
    Rcpp::traits::input_parameter< const double >::type th(thSEXP);
    rcpp_result_gen = Rcpp::wrap(prune_cpp(barrier, th));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_graphela_energy_cpp", (DL_FUNC) &_graphela_energy_cpp, 3},
    {"_graphela_stpd_cpp", (DL_FUNC) &_graphela_stpd_cpp, 4},
    {"_graphela_rss_cpp", (DL_FUNC) &_graphela_rss_cpp, 4},
    {"_graphela_findpath_cpp", (DL_FUNC) &_graphela_findpath_cpp, 7},
    {"_graphela_ridge_cpp", (DL_FUNC) &_graphela_ridge_cpp, 7},
    {"_graphela_find_shallow_cpp", (DL_FUNC) &_graphela_find_shallow_cpp, 1},
    {"_graphela_prune_cpp", (DL_FUNC) &_graphela_prune_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_graphela(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
