// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// energy
double energy(const arma::rowvec& state, const arma::rowvec& alpha, const arma::mat& beta);
RcppExport SEXP _graphela_energy(SEXP stateSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type state(stateSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(energy(state, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// stpd
arma::rowvec stpd(const arma::rowvec& state, const arma::rowvec& alpha, const arma::mat& beta, bool print);
RcppExport SEXP _graphela_stpd(SEXP stateSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type state(stateSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< bool >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(stpd(state, alpha, beta, print));
    return rcpp_result_gen;
END_RCPP
}
// rss
arma::mat rss(arma::rowvec alpha, arma::mat beta, const arma::uword n, const bool replace);
RcppExport SEXP _graphela_rss(SEXP alphaSEXP, SEXP betaSEXP, SEXP nSEXP, SEXP replaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< const bool >::type replace(replaceSEXP);
    rcpp_result_gen = Rcpp::wrap(rss(alpha, beta, n, replace));
    return rcpp_result_gen;
END_RCPP
}
// findpath
Rcpp::List findpath(const arma::rowvec& s0, const arma::rowvec& s1, const arma::rowvec& alpha, const arma::mat& beta, double temp, const double r, const arma::uword n);
RcppExport SEXP _graphela_findpath(SEXP s0SEXP, SEXP s1SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP tempSEXP, SEXP rSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type s0(s0SEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(findpath(s0, s1, alpha, beta, temp, r, n));
    return rcpp_result_gen;
END_RCPP
}
// ridge
arma::mat ridge(const arma::mat& sse, const arma::rowvec& alpha, const arma::mat& beta, double temp, const double r, const arma::uword n);
RcppExport SEXP _graphela_ridge(SEXP sseSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP tempSEXP, SEXP rSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sse(sseSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge(sse, alpha, beta, temp, r, n));
    return rcpp_result_gen;
END_RCPP
}
// find_shallow
arma::uword find_shallow(const arma::mat& pem);
RcppExport SEXP _graphela_find_shallow(SEXP pemSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pem(pemSEXP);
    rcpp_result_gen = Rcpp::wrap(find_shallow(pem));
    return rcpp_result_gen;
END_RCPP
}
// prune
Rcpp::List prune(arma::mat& pem, const double th);
RcppExport SEXP _graphela_prune(SEXP pemSEXP, SEXP thSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type pem(pemSEXP);
    Rcpp::traits::input_parameter< const double >::type th(thSEXP);
    rcpp_result_gen = Rcpp::wrap(prune(pem, th));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_graphela_energy", (DL_FUNC) &_graphela_energy, 3},
    {"_graphela_stpd", (DL_FUNC) &_graphela_stpd, 4},
    {"_graphela_rss", (DL_FUNC) &_graphela_rss, 4},
    {"_graphela_findpath", (DL_FUNC) &_graphela_findpath, 7},
    {"_graphela_ridge", (DL_FUNC) &_graphela_ridge, 6},
    {"_graphela_find_shallow", (DL_FUNC) &_graphela_find_shallow, 1},
    {"_graphela_prune", (DL_FUNC) &_graphela_prune, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_graphela(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
