# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

energy_cpp <- function(state, alpha, beta) {
    .Call(`_graphela_energy_cpp`, state, alpha, beta)
}

stpd_cpp <- function(state, alpha, beta, print = FALSE) {
    .Call(`_graphela_stpd_cpp`, state, alpha, beta, print)
}

rss_cpp <- function(alpha, beta, n = 10000L, replace = TRUE) {
    .Call(`_graphela_rss_cpp`, alpha, beta, n, replace)
}

findpath_cpp <- function(s0, s1, alpha, beta, temp = 1, r = 0.01, n = 10000L) {
    .Call(`_graphela_findpath_cpp`, s0, s1, alpha, beta, temp, r, n)
}

ridge_cpp <- function(sse, alpha, beta, temp = 1, r = 0.01, n = 10000L) {
    .Call(`_graphela_ridge_cpp`, sse, alpha, beta, temp, r, n)
}

find_shallow_cpp <- function(pem) {
    .Call(`_graphela_find_shallow_cpp`, pem)
}

prune_cpp <- function(pem, th = 0.2) {
    .Call(`_graphela_prune_cpp`, pem, th)
}

