# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

energy <- function(state, alpha, beta) {
    .Call('_graphela_energy', PACKAGE = 'graphela', state, alpha, beta)
}

stpd <- function(state, alpha, beta, print = FALSE) {
    .Call('_graphela_stpd', PACKAGE = 'graphela', state, alpha, beta, print)
}

rss <- function(alpha, beta, n = 20000L) {
    .Call('_graphela_rss', PACKAGE = 'graphela', alpha, beta, n)
}

searchR <- function(s0, s1, alpha, beta, temp = 1, r = 0.01, n = 10000L) {
    .Call('_graphela_searchR', PACKAGE = 'graphela', s0, s1, alpha, beta, temp, r, n)
}

ridge <- function(ss, alpha, beta, temp = 1, r = 0.01, n = 10000L) {
    .Call('_graphela_ridge', PACKAGE = 'graphela', ss, alpha, beta, temp, r, n)
}

find_shallow <- function(pem) {
    .Call('_graphela_find_shallow', PACKAGE = 'graphela', pem)
}

prune <- function(pem, th = 0.2) {
    .Call('_graphela_prune', PACKAGE = 'graphela', pem, th)
}

